Repository incubateind/programmersdate, pull requests merged in 2020-06, with the labels that each got.

#17 Jahnvi Thakkar Dotcom
  DotCOM.pptx
  DotCOM.txt
Labels: enhancement

#14 Team GrownUps
  mishra.yashrajs1288/.gitignore
  mishra.yashrajs1288/.nvmrc
  mishra.yashrajs1288/LICENSE
  mishra.yashrajs1288/README.md
  mishra.yashrajs1288/config/eslint.config.js
  mishra.yashrajs1288/config/jest.config.js
  mishra.yashrajs1288/config/jest.loadershim.js
  mishra.yashrajs1288/config/jest.preprocess.js
  mishra.yashrajs1288/extra/sampleData.csv
  mishra.yashrajs1288/flow.drawio.svg
  mishra.yashrajs1288/gatsby-config.js
  mishra.yashrajs1288/package.json
  mishra.yashrajs1288/sampleDotENV
  mishra.yashrajs1288/src/assets/images/gatsby-astronaut.jpg
  mishra.yashrajs1288/src/assets/stylesheets/application.scss
  mishra.yashrajs1288/src/assets/stylesheets/components/__components.scss
  mishra.yashrajs1288/src/assets/stylesheets/components/_footer.scss
  mishra.yashrajs1288/src/assets/stylesheets/components/_form.scss
  mishra.yashrajs1288/src/assets/stylesheets/components/_header.scss
  mishra.yashrajs1288/src/assets/stylesheets/components/_map.scss
  mishra.yashrajs1288/src/assets/stylesheets/pages/__pages.scss
  mishra.yashrajs1288/src/assets/stylesheets/pages/_home.scss
  mishra.yashrajs1288/src/assets/stylesheets/pages/_two.scss
  mishra.yashrajs1288/src/assets/stylesheets/pages/_upload.scss
  mishra.yashrajs1288/src/assets/stylesheets/settings/__settings.scss
  mishra.yashrajs1288/src/assets/stylesheets/settings/_colors.scss
  mishra.yashrajs1288/src/assets/stylesheets/settings/_fonts.scss
  mishra.yashrajs1288/src/assets/stylesheets/util/__util.scss
  mishra.yashrajs1288/src/assets/stylesheets/util/_helpers.scss
  mishra.yashrajs1288/src/components/Container.js
  mishra.yashrajs1288/src/components/Footer.js
  mishra.yashrajs1288/src/components/Header.js
  mishra.yashrajs1288/src/components/Layout.js
  mishra.yashrajs1288/src/components/Map.js
  mishra.yashrajs1288/src/components/Navbar.js
  mishra.yashrajs1288/src/components/RecordTable.js
  mishra.yashrajs1288/src/components/mapMaker.js
  mishra.yashrajs1288/src/components/sampleData.json
  mishra.yashrajs1288/src/data/map-services.js
  mishra.yashrajs1288/src/hooks/index.js
  mishra.yashrajs1288/src/hooks/useConfigureLeaflet.js
  mishra.yashrajs1288/src/hooks/useMapServices.js
  mishra.yashrajs1288/src/hooks/useRefEffect.js
  mishra.yashrajs1288/src/lib/map-services.js
  mishra.yashrajs1288/src/lib/map.js
  mishra.yashrajs1288/src/lib/util.js
  mishra.yashrajs1288/src/models/map-service.js
  mishra.yashrajs1288/src/pages/404.js
  mishra.yashrajs1288/src/pages/about.js
  mishra.yashrajs1288/src/pages/index.js
  mishra.yashrajs1288/src/pages/record.js
  mishra.yashrajs1288/src/pages/upload.js
  mishra.yashrajs1288/vercel.json
  mishra.yashrajs1288/yarn.lock
Labels: IncubateIND, programmersdate

#7 Web Blasters
  web-blasters/ReadMe
  web-blasters/Screenshot (20).png
  web-blasters/WhatsApp Image 2020-06-27 at 12.23.19 AM (1).jpeg
  web-blasters/WhatsApp Image 2020-06-27 at 12.23.19 AM.jpeg
  web-blasters/css/style.css
  web-blasters/img/bg.jpg
  web-blasters/img/logo.png
  web-blasters/ss1.jpeg
Labels: IncubateIND, enhancement, programmersdate

#5 Track a Bed
  map.php
  tab.sql
Labels: IncubateIND, programmersdate

#23 Closes #22
  README.md
Labels: IncubateIND, enhancement, programmersdate
